# Find the graph that are in the version dataset-1.ttl.trig
PREFIX vers: <https://github.com/VCityTeam/ConVer-G/Version#>
PREFIX ng: <https://github.com/VCityTeam/ConVer-G/Named-Graph#>

SELECT ?graph WHERE {
    ?vg vers:is-in-version vers:dataset-1.ttl.trig ;
        vers:is-version-of ?graph .
}