# Find the number of graphs in each version
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT ?version (COUNT(?graph) as ?countgraph) WHERE {
    ?vg prov:atLocation ?version ;
        prov:specializationOf ?graph .
} GROUP BY ?version