# Give the graph name (metadata) of the versioned graph containing the building 1 and its width
PREFIX building: <http://example.edu/Building#>
PREFIX schema: <http://schema.org/>

SELECT ?version ?p1 ?o1 ?type WHERE {
    GRAPH ?vg {
        building:1 ?p1 ?o1 ;
            schema:width ?type .
    }

    ?vg <http://www.w3.org/ns/prov#atLocation> ?version .
}