services:
  postgres:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sparqltosql
    volumes:
      - pg-volume:/var/lib/postgresql/data

  postgres-test:
    image: postgres:16.2
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres-test
      - POSTGRES_PASSWORD=password-test
      - POSTGRES_DB=sparqltosql-test
    volumes:
      - pg-volume-test:/var/lib/postgresql/data

  blazegraph:
    image: vcity/blazegraph-cors
    ports:
      - "9999:8080"
    container_name: blazegraph
    volumes:
      - ./blazegraph.properties:/data/blazegraph.properties

  sparql-to-sql-importer:
    build:
      context: quads-importer
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sparqltosql"
    ports:
      - "8080:8080"
    container_name: sparql-to-sql-importer

  sparql-to-sql-query:
    build:
      context: quads-query
      dockerfile: Dockerfile
      args:
        - DATASOURCE_URL=jdbc:postgresql://postgres:5432/sparqltosql
        - DATASOURCE_USERNAME=postgres
        - DATASOURCE_PASSWORD=password
    depends_on:
      - postgres
    environment:
      - "DATASOURCE_URL=jdbc:postgresql://postgres:5432/sparqltosql"
      - "DATASOURCE_USERNAME=postgres"
      - "DATASOURCE_PASSWORD=password"
    ports:
      - "8081:8081"
    container_name: sparql-to-sql-query

volumes:
  pg-volume:
    driver: local
  pg-volume-test:
    driver: local
