version: '3.0'

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sparqltosql
    volumes:
      - pg-volume:/var/lib/postgresql/data

  postgres-test:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres-test
      - POSTGRES_PASSWORD=password-test
      - POSTGRES_DB=sparqltosql-test
    volumes:
      - pg-volume-test:/var/lib/postgresql/data

  blazegraph:
    image: vcity/blazegraph-cors
    ports:
      - "9999:8080"
    container_name: blazegraph
    volumes:
      - ./blazegraph.properties:/data/blazegraph.properties

  sparql-to-sql:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sparqltosql"
    ports:
      - "8080:8080"
    container_name: sparql-to-sql

volumes:
  pg-volume:
    driver: local
  pg-volume-test:
    driver: local
