version: '3.0'

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sparqltosql
    volumes:
      - pg-volume:/var/lib/postgresql/data

  postgres-test:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres-test
      - POSTGRES_PASSWORD=password-test
      - POSTGRES_DB=sparqltosql-test
    volumes:
      - pg-volume-test:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    container_name: sonarqube

volumes:
  pg-volume:
    driver: local
  pg-volume-test:
    driver: local
