# CityGML 2.0 prefixes
PREFIX bldg: <https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/building#>

# Return the number of features within all version
SELECT (COUNT(?object) AS ?number)
WHERE {
    ?graph a <https://github.com/VCityTeam/SPARQL-to-SQL/GraphType#Version> .
    GRAPH ?graph {
      ?object a bldg:Building .
    }
}