# Return the number of Buildings by version and graph names
SELECT ?graph (COUNT(?object) AS ?number)
WHERE {
    GRAPH ?graph {
        ?object a "https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/building#Building" .
    }
}
GROUP BY ?graph