# Across multiple concurrent city versions, what is the maximum known height of a particular building?
SELECT (MAX(?height) AS ?maximum) WHERE {
	GRAPH ?validity {
  		<https://github.com/VCityTeam/UD-Graph/LYON_1ER_BATI_2015-1_bldg#BU_69381AB243_1> <http://www.opengis.net/citygml/building/2.0/building#AbstractBuilding.measuredHeight> ?height .
  	}
}


# TODO
SELECT (MAX(?height) AS ?maximum) WHERE {
	GRAPH ?validity {
  		<https://github.com/VCityTeam/UD-Graph/LYON_1ER_BATI_2015-1_bldg#BU_69381AB243_1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.opengis.net/ont/geosparql#Geometry> ;
            <http://www.opengis.net/citygml/building/2.0/building#AbstractBuilding.measuredHeight> ?height .
  	}
}

# TODO  
SELECT (SUM(?height) AS ?sum) WHERE {
    ?validity <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://github.com/VCityTeam/SPARQL-to-SQL/graph-type#Validity> .
	GRAPH ?validity {
  		<https://github.com/VCityTeam/UD-Graph/LYON_1ER_BATI_2015-1_bldg#BU_69381AB243_1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.opengis.net/ont/geosparql#Geometry> ;
            <http://www.opengis.net/citygml/building/2.0/building#AbstractBuilding.measuredHeight> ?height .
  	}
}

# Across multiple concurrent versions, find all the quads that were not valid once (or more) before the '2023-07-03 13:18'
SELECT ?version ?subject ?property ?object WHERE {
    ?version <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://github.com/VCityTeam/SPARQL-to-SQL/graph-type#Version> .
    ?version <https://github.com/VCityTeam/SPARQL-to-SQL/graph-type#commited_at> ?date_commit .
	GRAPH ?version {
	    ?subject ?property ?object .
  	}
  	FILTER(?date_commit < '2023-07-03 13:18')
}
