# SPARQL query to get the average rating of reviews per version
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT ?version (AVG(?rating) as ?avgrating) WHERE {
  GRAPH ?vg {
      ?s a bsbm:Review ;
  			bsbm:rating3 ?rating .
  }

  GRAPH <https://github.com/VCityTeam/ConVer-G/Named-Graph#Metadata> {
    ?vg prov:atLocation ?version .
  }
} GROUP BY ?version