# Find the number of versions
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT (COUNT(?version) as ?countversion) WHERE {
  GRAPH <https://github.com/VCityTeam/ConVer-G/Named-Graph#Metadata> {
        ?vg prov:atLocation ?version .
  }
}