# Find the number of rating of reviews in each graph
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT ?graph (COUNT(?rating) as ?countrating) WHERE {
  GRAPH ?vg {
      ?s a bsbm:Review ;
  			bsbm:rating3 ?rating .
  }

  GRAPH <https://github.com/VCityTeam/ConVer-G/Named-Graph#Metadata> {
    ?vg prov:specializationOf ?graph .
  }
} GROUP BY ?graph