# Common prefixes
PREFIX owl:    <http://www.w3.org/2002/07/owl#>

# CityGML 2.0 prefixes
PREFIX core: <https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/core#>

# Dataset prefixes
PREFIX vt:    <https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Datasets/GratteCiel_Workspace_2009_2018/3.0/GratteCiel#>

# Return the number of features within a version
SELECT (COUNT(?object) AS ?number)
WHERE {
    vt:GratteCiel_2012_split.ttl a <https://github.com/VCityTeam/SPARQL-to-SQL/GraphType#Version> .
    GRAPH vt:GratteCiel_2012_split.ttl {
      ?subject a core:CityModel ;
        a ?subjectType .

      FILTER(?subjectType != owl:NamedIndividual)
    }
}