# Find the number of rating of reviews in each version
PREFIX schema: <http://schema.org/>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT ?version (AVG(?height) as ?avgheight) WHERE {
  GRAPH ?vg {
    ?s schema:height ?height .
  }

  GRAPH <https://github.com/VCityTeam/ConVer-G/Named-Graph#Metadata> {
    ?vg prov:atLocation ?version .
  }
} GROUP BY ?version