# Find the number of graphs in each version
PREFIX vers: <https://github.com/VCityTeam/ConVer-G/Version#>

SELECT ?version (COUNT(?graph) as ?countgraph) WHERE {
  GRAPH <https://github.com/VCityTeam/ConVer-G/Named-Graph#Metadata> {
    ?vg vers:is-in-version ?version ;
        vers:is-version-of ?graph .
  }
} GROUP BY ?version