# Find the number of graph
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT (COUNT(?graph) as ?countgraph) WHERE {
  GRAPH <https://github.com/VCityTeam/ConVer-G/Named-Graph#Metadata> {
        ?vg prov:specializationOf ?graph .
  }
}