# Find the graph that are in the version dataset-1.ttl.trig
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT ?graph WHERE {
  GRAPH <https://github.com/VCityTeam/ConVer-G/Named-Graph#Metadata> {
    ?vg prov:atLocation "dataset-1.ttl.trig" ;
        prov:specializationOf ?graph .
  }
}