# The two largest heights of building 1 across all versioned graphs
PREFIX schema: <http://schema.org/>
PREFIX building: <http://example.edu/Building#>

SELECT ?h WHERE {
  GRAPH ?g {
      building:1 schema:height ?h .
  }
    FILTER(?g != <https://github.com/VCityTeam/ConVer-G/Named-Graph#Metadata>)

} ORDER BY DESC(?h) LIMIT 2
