# Find the number of versions
PREFIX vers: <https://github.com/VCityTeam/ConVer-G/Version#>

SELECT (COUNT(?version) as ?countversion) WHERE {
  GRAPH <https://github.com/VCityTeam/ConVer-G/Named-Graph#Metadata> {
        ?vg vers:is-in-version ?version .
  }
}