# SPARQL Query to find all the named graphs that contain a rating greater than 4
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>

SELECT ?vg ?s ?rating WHERE {
    GRAPH ?vg {
      ?s bsbm:rating3 ?rating .
      FILTER(?rating > 4)
    }
    FILTER(?vg != <https://github.com/VCityTeam/ConVer-G/Named-Graph#Metadata>)
}