# Query the graph store for all quads in a specific versioned graph with a given subject and a join on the subject (predicate might be equal to predicate2 and object might be equal to object2)
SELECT ?p ?o WHERE {
    GRAPH <https://github.com/VCityTeam/ConVer-G/Versioned-Named-Graph#a156e4f5c5cb3dda5b72fb64c4264de925a10fbdefa8ae5b7066e69027edbd48> {
      <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature287> ?p ?o ;
        ?p2 ?o2 .
    }
}