# SPARQL Query: count the number of subject by rating
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
SELECT ?rating (COUNT(?s) as ?counts) WHERE {
  GRAPH ?vg {
      ?s a bsbm:Review ;
  			bsbm:rating3 ?rating .
  }
  FILTER(?vg != <https://github.com/VCityTeam/ConVer-G/Named-Graph#Metadata>)
} GROUP BY ?rating