# Find the versions that are in the graph Test
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX ng: <https://github.com/VCityTeam/ConVer-G/Named-Graph#>

SELECT ?version WHERE {
  GRAPH <https://github.com/VCityTeam/ConVer-G/Named-Graph#Metadata> {
    ?vg prov:atLocation ?version ;
        prov:specializationOf ng:Test .
  }
}