# Find the graph that are in the version dataset-1.ttl.trig
PREFIX ng: <https://github.com/VCityTeam/ConVer-G/Named-Graph#>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT ?graph WHERE {
    ?vg prov:atLocation "dataset-1.ttl.trig" ;
        prov:specializationOf ?graph .
}