# Find the versions that are in the graph Test
PREFIX vers: <https://github.com/VCityTeam/ConVer-G/Version#>
PREFIX ng: <https://github.com/VCityTeam/ConVer-G/Named-Graph#>

SELECT ?version WHERE {
    ?vg vers:is-in-version ?version ;
        vers:is-version-of ng:Test .
}