# Find the versions that are in the graph Test
PREFIX ng: <https://github.com/VCityTeam/ConVer-G/Named-Graph#>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT ?version WHERE {
    ?vg prov:atLocation ?version ;
        prov:specializationOf ng:Test .
}