# Find the number of height in each graph
PREFIX schema: <http://schema.org/>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT ?graph (COUNT(?height) as ?countheight) WHERE {
    GRAPH ?vg {
        ?s schema:height ?height .
    }
  ?vg prov:specializationOf ?graph .
} GROUP BY ?graph