name: Run tests on push (development)

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run docker-compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "./docker-compose.yml"
        services: |
          postgres
          postgres-test

    - name: Set up JDK 21 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64

    - name: Run unit tests
      run: mvn test

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Wait for Blazegraph to be ready
        run: |
          time=0
          until curl -sSf 'http://localhost:9999/blazegraph/sparql' > /dev/null; do
            echo "Waiting for Blazegraph..."
            time=$((time+5))
            sleep 5
            if [ $time -gt 60 ]; then
              echo "Blazegraph did not start in time"
              exit 1
            fi
          done

      - name: Initialize blazegraph datasets
        run: |
          find quads-query/src/test/resources/dataset/theoretical -type f -name "*.ttl.trig" -print0 | while IFS= read -r -d '' file
          do
            curl -X POST --location 'http://localhost:9999/blazegraph/sparql' \
              --header 'Content-Type:application/x-trig' \
              --connect-timeout 60 \
              --data-binary @"$file"
          done

      - name: Wait for QuaDer to be ready
        run: |
          time=0
          until curl -sSf -X DELETE --location "http://localhost:8080/import/metadata" > /dev/null; do
            echo "Waiting for QuaDer..."
            time=$((time+5))
            sleep 5
            if [ $time -gt 60 ]; then
              echo "Blazegraph did not start in time"
              exit 1
            fi
            sleep 1
          done

      - name: Initialize QuaDer datasets
        run: |
          find quads-query/src/test/resources/dataset/relational -type f -name "*.ttl.trig" -print0 | while IFS= read -r -d '' file
          do
          curl --location 'http://localhost:8080/import/version' \
            --header 'Content-Type: multipart/form-data' \
            --connect-timeout 60 \
            --form file=@"$file"
          done

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Run integration tests
        run: mvn verify