# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image Quads Query

on:
  push:
    tags:
      - "qq-v*"

jobs:
  test:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4

    - name: Run docker-compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "./docker-compose.yml"

    - name: Wait for Blazegraph to be ready
      run: |
        until curl -sSf 'http://localhost:9999/blazegraph/sparql' > /dev/null; do
          echo "Waiting for Blazegraph..."
          sleep 5
        done

    - name: Initialize blazegraph datasets
      run: |
        find quads-query/src/test/resources/dataset/theoretical -type f -name "*.ttl.trig" -print0 | while IFS= read -r -d '' file
        do
          curl -X POST --location 'http://localhost:9999/blazegraph/sparql' \
            --header 'Content-Type:application/x-trig' \
            --connect-timeout 60 \
            --data-binary @"$file"
        done

    - name: Set up JDK 21 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64

    - name: Run tests
      run: mvn test -pl quads-query

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      # Checkout the repo
      # https://github.com/actions/checkout
      - name: Check out the repo
        uses: actions/checkout@v4

      # Log in to Docker Hub
      # https://github.com/docker/login-action
      # Uses the login and a DockerHub token
      # https://hub.docker.com/settings/security
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: vcity/quads-query

      # Build and push Docker image
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: quads-query
          file: ./quads-query/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}