name: Run tests on push (development)

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Wait for Blazegraph to be ready
        run: |
          until curl -sSf 'http://localhost:9999/blazegraph/sparql' > /dev/null; do
            echo "Waiting for Blazegraph..."
            sleep 5
          done

      - name: Initialize blazegraph datasets
        run: |
          find quads-query/src/test/resources/dataset/theoretical -type f -name "*.ttl.trig" -print0 | while IFS= read -r -d '' file
          do
            curl -X POST --location 'http://localhost:9999/blazegraph/sparql' \
              --header 'Content-Type:application/x-trig' \
              --connect-timeout 60 \
              --data-binary @"$file"
          done

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Run tests
        run: mvn test