name: Docker Compose Action

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Initialize databases datasets
        run: |
          find quads-query/src/test/resources/dataset/theoretical -type f -name "*.ttl.trig" -print0 | while IFS= read -r -d '' file
          do
            printf "%s\n$(date +%FT%T) - [Triple Store] $file."
            start=$(date +%s%3N)
            curl -X POST --location 'http://localhost:9999/blazegraph/sparql' \
            --header 'Content-Type:application/x-trig' \
            --connect-timeout 60 \
            --data-binary @"$file"
            end=$(date +%s%3N)
            printf "\n%s$(date +%FT%T) - [Measure] (Import BG $file):$((end-start))ms;"
          done

      - name: Run tests
        run: mvn test